- name: Install commonly used packages
  dnf: name={{ package }} state=present
  with_items:
    - nano
    - mc
    - bash-completion
    - strace
    - wget
    - traceroute
  loop_control:
    loop_var: package
